export const approvePageStyles = {
  page: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    backgroundColor: "#f4f4f5",
    padding: 0,
    margin: 0,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: "1rem",
    boxShadow:
      "0 4px 6px -1px rgba(0,0,0,0.07), 0 2px 4px -2px rgba(0,0,0,0.05), 0 0 0 1px rgba(0,0,0,0.05)",
    padding: "2rem",
    maxWidth: "26rem",
    width: "100%",
  },
  header: {
    textAlign: "left" as const,
    marginBottom: "1.5rem",
  },
  appLogo: {
    marginBottom: "1.25rem",
  },
  heading: {
    fontSize: "1.25rem",
    fontWeight: 600 as const,
    color: "#18181b",
    margin: 0,
    lineHeight: 1.4,
  },
  divider: {
    height: "1px",
    backgroundColor: "#e4e4e7",
    border: "none",
    margin: "0 0 1.25rem 0",
  },
  integrationList: {
    listStyle: "none" as const,
    margin: "0 0 1.25rem 0",
    padding: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.375rem",
  },
  integrationItem: {
    display: "flex",
    alignItems: "center",
    gap: "0.625rem",
    padding: "0.375rem 0.625rem",
    backgroundColor: "#fafafa",
    borderRadius: "0.375rem",
  },
  integrationIcon: {
    width: "20px",
    height: "20px",
    flexShrink: 0,
  },
  integrationName: {
    fontSize: "0.8125rem",
    fontWeight: 500 as const,
    color: "#18181b",
  },
  sectionLabel: {
    fontSize: "0.75rem",
    fontWeight: 500 as const,
    color: "#a1a1aa",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    margin: "0 0 0.5rem 0",
  },
  permissionList: {
    listStyle: "none" as const,
    margin: "0 0 1.25rem 0",
    padding: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.375rem",
  },
  permissionItem: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "0.8125rem",
    color: "#3f3f46",
    lineHeight: 1.5,
  },
  checkIcon: {
    color: "#22c55e",
    fontSize: "0.875rem",
    flexShrink: 0,
    fontWeight: 700 as const,
  },
  meta: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.25rem",
    marginBottom: "1.5rem",
    fontSize: "0.8125rem",
    color: "#71717a",
  },
  buttonRow: {
    display: "flex",
    gap: "0.75rem",
    marginBottom: "1rem",
  },
  approveButton: {
    flex: 1,
    padding: "0.625rem 1rem",
    fontSize: "0.875rem",
    fontWeight: 600 as const,
    color: "#fff",
    backgroundColor: "#18181b",
    border: "none",
    borderRadius: "0.5rem",
    cursor: "pointer",
    lineHeight: 1.5,
  },
  denyButton: {
    flex: 1,
    padding: "0.625rem 1rem",
    fontSize: "0.875rem",
    fontWeight: 500 as const,
    color: "#3f3f46",
    backgroundColor: "#fff",
    border: "1px solid #d4d4d8",
    borderRadius: "0.5rem",
    cursor: "pointer",
    lineHeight: 1.5,
  },
  finePrint: {
    fontSize: "0.75rem",
    color: "#a1a1aa",
    textAlign: "center" as const,
    lineHeight: 1.6,
    margin: 0,
  },
  reasonBlock: {
    margin: "0 0 1.25rem 0",
    padding: "0.625rem 0.75rem",
    borderLeft: "3px solid #d4d4d8",
    backgroundColor: "#fafafa",
    borderRadius: "0 0.375rem 0.375rem 0",
    fontSize: "0.8125rem",
    fontStyle: "italic" as const,
    color: "#52525b",
    lineHeight: 1.6,
  },
  reasonLabel: {
    display: "block",
    fontSize: "0.6875rem",
    fontWeight: 600 as const,
    fontStyle: "normal" as const,
    color: "#a1a1aa",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    marginBottom: "0.25rem",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.625rem",
    cursor: "pointer",
    flex: 1,
  },
  checkbox: {
    width: "16px",
    height: "16px",
    flexShrink: 0,
    accentColor: "#18181b",
    cursor: "pointer",
  },
  textarea: {
    width: "100%",
    minHeight: "4rem",
    padding: "0.5rem 0.625rem",
    fontSize: "0.8125rem",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    border: "1px solid #e4e4e7",
    borderRadius: "0.375rem",
    resize: "vertical" as const,
    outline: "none",
    color: "#18181b",
    lineHeight: 1.5,
    boxSizing: "border-box" as const,
    marginBottom: "1.25rem",
  },
  resultIcon: {
    width: "3rem",
    height: "3rem",
    borderRadius: "50%",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.25rem",
    marginBottom: "0.75rem",
  },
  resultTitle: {
    fontSize: "1.125rem",
    fontWeight: 600 as const,
    color: "#18181b",
    margin: "0 0 0.375rem 0",
  },
  resultHint: {
    fontSize: "0.875rem",
    color: "#71717a",
    margin: 0,
    lineHeight: 1.6,
  },
  errorText: {
    fontSize: "0.875rem",
    color: "#dc2626",
    lineHeight: 1.6,
  },
};

export type ApprovePageStyles = typeof approvePageStyles;
